# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f71b7ed4c87aa43c7fc8f5ff8db754a64287a28b5db2ad509e27fe59b967cadff1c7aec9e9ff4822177b710f88414a377b871fac0616f641fb85910ca809a48

test:
  secret_key_base: 2059863d4003938685f43e200d07cf4c7141f2afb2c16da986d9d4be734c6464d6cbd9a43e5a7dddbf5e138f4f034c10171879eeaaf09e23e9cf35b8e071d1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
